aplikasi/__init__.py
import pandas as pd
from flask import Flask, render_template, abort
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_login import current_user, login_required
from flask_admin import Admin
from datetime import datetime
from konfigurasi import DevConfig


db = SQLAlchemy() # db = SQLAlchemy(session_options={"autoflush": False})
migrate = Migrate()
bootstrap = Bootstrap()
moment = Moment()
adm = Admin()

def buat_app(nama_konfigurasi):
    
    apl = Flask(__name__)
    apl.config.from_object(nama_konfigurasi)

    db.init_app(apl)
    migrate.init_app(apl, db)
    bootstrap.init_app(apl)
    moment.init_app(apl)
    adm.init_app(apl)

    from .utama import buat_modul as induk_modul
    from .otentikasi import buat_modul as auth_modul
    from .wilayah import buat_modul as wilayah_modul
    from .anggota import buat_modul as anggota_modul
    from .sapi import buat_modul as sapi_modul
    from .inseminasi import buat_modul as ib_modul
    from .pkb import buat_modul as pkb_modul
    from .ann import buat_modul as ann_modul
    
    induk_modul(apl)
    auth_modul(apl)
    wilayah_modul(apl)
    anggota_modul(apl)
    sapi_modul(apl)
    ib_modul(apl)
    pkb_modul(apl)
    ann_modul(apl)

    apl.register_error_handler(404, laman_tak_ditemukan)
    apl.register_error_handler(403, akses_ditolak)
    apl.register_error_handler(500, internal_error)

    @apl.before_request
    def before_request():
        if current_user.is_authenticated:
            current_user.last_login = datetime.utcnow()
            db.session.commit()
    
    return apl

def laman_tak_ditemukan(error):
    return render_template('/galat/404.html'), 404
def internal_error(error):
    db.session.rollback()
    return render_template('/galat/500.html'), 500
def akses_ditolak(error):
    return render_template('/galat/403.html'), 403

import functools

def has_role(name):
    def real_decorator(f):
        def wraps(*args, **kwargs):
            if current_user.has_role(name):
                return f(*args, **kwargs)
            else:
                abort(403)
        return functools.update_wrapper(wraps, f)
    return real_decorator

aplikasi/anggota/__init__.py
from aplikasi import db, adm
from flask_admin.contrib.sqla import ModelView
from aplikasi.anggota import anggota_models as manggota
from aplikasi.anggota import anggota_controllers as canggota



def buat_modul(apl, **kwargs):
    from .anggota_controllers import anggota_bp
    apl.register_blueprint(anggota_bp)
    # adm.add_view(ModelView(manggota.Anggota, db.session))
    adm.add_view(canggota.AnggotaList(canggota.Anggota, db.session))

aplikasi/ann/__init__.py
from sklearn.metrics import (
    accuracy_score, cohen_kappa_score,
    classification_report, confusion_matrix, roc_auc_score
)
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.utils import resample
from sklearn.preprocessing import MinMaxScaler
from aplikasi import db, adm
from flask_admin.contrib.sqla import ModelView
# from aplikasi.ann import ann_controllers as cann
# from aplikasi.ann import ann_models as mann


def buat_modul(apl, **kwargs):
    from .ann_controllers import ann_bp
    apl.register_blueprint(ann_bp)

aplikasi/inseminasi/__init__.py
from aplikasi import db, adm
from flask_admin.contrib.sqla import ModelView
from aplikasi.inseminasi import inseminasi_models as mib
from aplikasi.inseminasi import inseminasi_controllers as cib


def buat_modul(apl, **kwargs):
    from .inseminasi_controllers import ib_bp
    apl.register_blueprint(ib_bp)
    adm.add_view(cib.InseminasiList(cib.Inseminasi, db.session))

aplikasi/otentikasi/__init__.py
from flask_login import LoginManager
from flask_bcrypt import Bcrypt

login_manager = LoginManager()
login_manager.login_view = "auth.masuk"
login_manager.login_message = "Silahkan login dahulu"
login_manager.login_message_category = "info"
bcrypt = Bcrypt()

@login_manager.user_loader
def load_user(id):
    from aplikasi.user.user_models import User
    return User.query.get(id)

def buat_modul(apl, **kwargs):
    login_manager.init_app(apl)
    bcrypt.init_app(apl)

    from .auth_controllers import auth_bp
    apl.register_blueprint(auth_bp)

aplikasi/pkb/__init__.py
from aplikasi import db, adm
from flask_admin.contrib.sqla import ModelView
from aplikasi.pkb import pkb_models as mpkb
from aplikasi.pkb import pkb_controllers as cpkb


def buat_modul(apl, **kwargs):
    from .pkb_controllers import pkb_bp
    apl.register_blueprint(pkb_bp)
    adm.add_view(cpkb.PkbList(cpkb.Pkb, db.session))

aplikasi/sapi/__init__.py
from aplikasi import db, adm
from flask_admin.contrib.sqla import ModelView
from aplikasi.sapi import sapi_models as msapi
from aplikasi.sapi import sapi_controllers as csapi



def buat_modul(apl, **kwargs):
    from .sapi_controllers import sapi_bp
    apl.register_blueprint(sapi_bp)
    # adm.add_view(ModelView(msapi.Sapi, db.session))
    adm.add_view(csapi.SapiList(csapi.Sapi, db.session))

aplikasi/user/__init__.py
from aplikasi import db, adm
from flask_admin.contrib.sqla import ModelView
from aplikasi.user import user_models as muser
from aplikasi.user import user_controllers as cuser

# adm.add_view(ModelView(muser.User, db.session))
adm.add_view(cuser.UserAdminView(cuser.User, db.session))

def buat_modul(apl, **kwargs):
    from .user_controllers import pengguna_bp
    apl.register_blueprint(pengguna_bp)
    

aplikasi/utama/__init__.py
def buat_modul(apl, **kwargs):
    from .controllers import induk_bp
    apl.register_blueprint(induk_bp)

aplikasi/utama/controllers.py
from flask import render_template, Blueprint, flash, redirect, url_for
from aplikasi import login_required

induk_bp = Blueprint(
    'induk',
    __name__,
    template_folder='../templates/utama',
    url_prefix="/"
)

@induk_bp.route('/')
@login_required
def home():
    return render_template('home.html')

aplikasi/wilayah/__init__.py
from aplikasi import db, adm
from flask_admin.contrib.sqla import ModelView
from aplikasi.wilayah import wilayah_models as mwilayah


def buat_modul(apl, **kwargs):
    from .wilayah_controllers import wilayah_bp
    apl.register_blueprint(wilayah_bp)
    adm.add_view(ModelView(mwilayah.Wilayah, db.session))

aplikasi/templates/anggota/anggota_add.html
{% extends 'layout.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block isi_content %}
    <h1>Menambah Anggota</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(fm) }}
        </div>
    </div>
{% endblock %}

aplikasi/templates/anggota/anggota_index.html
{% extends 'app.html' %}

{% block konten %}
    <div class="col-xxl-4 col-lg-12">
        <div class="panel">
            <div class="panel-heading">
            <h3 class="panel-title">Data Anggota</h3>
            </div>

            <div class="panel-body">
                <table class="table table-hover dataTable table-striped w-full" data-plugin="dataTable">
                    <thead>
                        <tr>
                            <th>Nomor</th>
                            <th>Nama</th>
                            <th>Wilayah</th>
                            <th>Terakhir Update</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Nomor</th>
                            <th>Nama</th>
                            <th>Wilayah</th>
                            <th>Terakhir Update</th>
                            <th>Opsi</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for d in data %}
                            <tr>
                                <td>{{ d.no_anggota }}</td>
                                <td>{{ d.namaanggota }}</td>
                                <th>{{ d.wilayah }}</th>
                                <td>{{ d.updated_at }}</td>                      
                                <td>
                                <a href="#"  class="btn btn-outline btn-xs btn-info">Detail</a>
                                <a href="#"  class="btn btn-outline btn-xs btn-info">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
{% endblock %}

aplikasi/templates/ann/hasil.html
{% extends 'app.html' %}

{% block konten %}
    <div class="col-xxl-4 col-lg-12">
        <div class="panel">
           
            <div class="panel-body">
              <div class="card border border-primary">
              <div class="card-block">
                <h4 class="card-title">Perhatian</h4>
                <p class="card-text">Melakukan perhitungan prediksi akan membutuhkan waktu yang cukup lama, harap sabar.</p>
                <p> Skor Akurasi pemodelan saat ini = {{ akurasi }} <br/> Skor ROC saat ini = {{ roc }} <br/> Confusion Matrix = {{ cm }}</p>
                <a href="{{ url_for('ann.prediksi') }}" class="btn btn-outline btn-primary btn btn-default btn-outline float-right">Hitung Prediksi</a> </div>
              </div>
            </div>
             <div class="panel-heading">
            <h3 class="panel-title">Hasil Prediksi</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover dataTable table-striped w-full" data-plugin="dataTable">
                    <thead>
                        <tr>
                            <th>Sapi</th>
                            <th>Pemilik</th>
                            <th>Prediksi Estrus</th>
                            <th>Pada Tanggal</th>
                            <th>Wilayah</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Sapi</th>
                            <th>Pemilik</th>
                            <th>Prediksi Estrus</th>
                            <th>Pada Tanggal</th>
                            <th>Wilayah</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for data in prediksi %}
                            <tr>
                                <td>{{ data[0] }}</td>
                                <td>{{ data[1] }}</td>
                                <td>{% if data[2] == 1 %} Estrus {% else %} Tidak Estrus {% endif %}</td>
                                <td>{{ data[3] }}</td>
                                <td>{{ data[4] }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

aplikasi/templates/ann/prediksi.html
{% extends 'layout.html' %}

{% block isi_content %}
    <h1>Menambah Wilayah {{ x }} dan {{ y }}</h1>
    <div class="row">
        <div class="col-md-4">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Sapi</th>
                    <th scope="col">Pemilik</th>
                    <th scope="col">Prediksi Estrus</th>
                    <th scope="col">Pada Tanggal</th>
                    <th scope="col">Wilayah</th>
                  </tr>
                </thead>
                <tbody>
                {% for data in prediksi %}
                  <tr>
                    <td>{{ data[0] }}</td>
                    <td>{{ data[1] }}</td>
                    <td>{{ data[2] }}</td>
                    <td>{{ data[3] }}</td>
                    <td>{{ data[4] }}</td>
                    <td>
                        {% if data[0]==1 %} Birahi {% else %} Tidak Birahi {% endif %}
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
{% endblock %}

aplikasi/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% if title %}{{ title }} - Aplikasi Prediksi Estrus Sapi{% else %}{{ ('Selamat Datang - Aplikasi Prediksi Estrus Sapi') }}{% endif %}</title>
    <!-- CSS -->
    <link rel="apple-touch-icon" href="/static/assets/images/apple-touch-icon.png">
    <link rel="shortcut icon" href="/static/assets/images/favicon.ico">
    
    <link rel="stylesheet" href="/static/global/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/global/css/bootstrap-extend.min.css">
    <link rel="stylesheet" href="/static/assets/css/site.min.css">
    <link rel="stylesheet" href="/static/assets/css/alerts.css">
    
    <link rel="stylesheet" href="/static/assets/examples/css/login.css">
    
    <link rel="stylesheet" href="/static/global/fonts/web-icons/web-icons.min.css">
    <link rel="stylesheet" href="/static/global/fonts/brand-icons/brand-icons.min.css">
</head>
<body class="animsition page-login layout-full page-dark">

    <!-- Page -->
    
    {% block konten %} 
    {% endblock  %}

    <!-- End Page -->

    <script src="/static/global/vendor/jquery/jquery.js"></script>
    <script src="/static/global/vendor/popper-js/umd/popper.min.js"></script>
    <script src="/static/global/vendor/bootstrap/bootstrap.js"></script>
</body>
</html>

aplikasi/templates/inseminasi/inseminasi_add.html
{% extends 'app.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block konten %}
    <div class="col-xxl-4 col-lg-12">
        <div class="panel">
            <div class="panel-heading">
            <h3 class="panel-title">Transaksi Inseminasi Buatan</h3>
            </div>
            <div class="col-lg-6 offset-lg-3">
                {{ wtf.quick_form(fm) }}
                <br/>
            </div>
        </div>
    </div>
{% endblock %}

aplikasi/templates/inseminasi/inseminasi_index.html
{% extends 'app.html' %}

{% block konten %}
    <div class="col-xxl-4 col-lg-12">
        <div class="panel">
            <div class="panel-heading">
            <h3 class="panel-title">Data Sapi</h3>
            </div>

            <div class="panel-body">
                <table class="table table-hover dataTable table-striped w-full" data-plugin="dataTable">
                    <thead>
                        <tr>
                            <th>ID Sapi</th>
                            <th>RPF</th>
                            <th>Perilaku</th>
                            <th>IB ke-</th>
                            <th>Jarak IB</th>
                            <th>Laktasi</th>
                            <th>Tgl IB</th>
                            <th>Kode Semen</th>
                            <th>Batch</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID Sapi</th>
                            <th>RPF</th>
                            <th>Perilaku</th>
                            <th>IB ke-</th>
                            <th>Jarak IB</th>
                            <th>Laktasi</th>
                            <th>Tgl IB</th>
                            <th>Kode Semen</th>
                            <th>Batch</th>
                            <th>Opsi</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for d in data %}
                            <tr>
                                <td>{{ d.sapi }}</td>
                                <td>{{ d.rpf }}</td>
                                <th>{{ d.perilaku }}</th>
                                <td>{{ d.ib_ke }}</td>
                                <td>{{ d.jarak_ib }}</td>
                                <td>{{ d.laktasi }}</td>
                                <td>{{ d.tgl_ib }}</td>
                                <td>{{ d.sem_code }}</td>
                                <td>{{ d.batch }}</td>                        
                                <td>
                                <a href="#"  class="btn btn-outline btn-xs btn-info">Detail</a>
                                <a href="#"  class="btn btn-outline btn-xs btn-info">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
{% endblock %}

aplikasi/templates/layout.html
{% extends '/bootstrap/base.html' %}
{% block title %}
    {% if title %}{{ title }} - Aplikasi Prediksi Estrus Sapi{% else %}{{ ('Selamat Datang - Aplikasi Prediksi Estrus Sapi') }}{% endif %}
{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"/>
{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('induk.home') }}">Narotama</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('induk.home') }}">Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.masuk') }}">Masuk</a></li>
                    {% else %}
                    <li>
                        {% if current_user.last_login %}
                        <a>Login terakhir : {{ moment(current_user.last_login).format('LLLL') }}</a>
                        {% endif %}
                    </li>
                    <li><a href="{{ url_for('auth.keluar') }}">Keluar</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with pesan = get_flashed_messages() %}
        {% if pesan %}
            {% for psn in pesan %}
            <div class="alert alert-info" role="alert">{{ psn }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# Flask-Bootstrap harus pake block dgn nama 'content' dengan sub block 'sembarang_content' #}
        {% block isi_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
     <script>
            $(document).ready(function() {
                $('#example').DataTable();
            } );
    </script>
{% endblock %}

aplikasi/templates/menu.html
{% block menu %}
    <nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">
    
      <div class="navbar-header">
        <button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided"
          data-toggle="menubar">
          <span class="sr-only">Toggle navigation</span>
          <span class="hamburger-bar"></span>
        </button>
        <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-collapse"
          data-toggle="collapse">
          <i class="icon wb-more-horizontal" aria-hidden="true"></i>
        </button>
        <div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
          <img class="navbar-brand-logo" src="assets/images/logo.png" title="Remark">
          <span class="navbar-brand-text hidden-xs-down"> KPSP Setia Kawan</span>
        </div>
        <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-search"
          data-toggle="collapse">
          <span class="sr-only">Toggle Search</span>
          <i class="icon wb-search" aria-hidden="true"></i>
        </button>
      </div>
    
      <div class="navbar-container container-fluid">
        <!-- Navbar Collapse -->
        <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
          <!-- Navbar Toolbar -->
          <ul class="nav navbar-toolbar">
            <li class="nav-item hidden-float" id="toggleMenubar">
              <a class="nav-link" data-toggle="menubar" href="#" role="button">
                <i class="icon hamburger hamburger-arrow-left">
                  <span class="sr-only">Toggle menubar</span>
                  <span class="hamburger-bar"></span>
                </i>
              </a>
            </li>
            <li class="nav-item hidden-sm-down" id="toggleFullscreen">
              <a class="nav-link icon icon-fullscreen" data-toggle="fullscreen" href="#" role="button">
                <span class="sr-only">Toggle fullscreen</span>
              </a>
            </li>
            <li class="nav-item hidden-float">
              <a class="nav-link icon wb-search" data-toggle="collapse" href="#" data-target="#site-navbar-search"
                role="button">
                <span class="sr-only">Toggle Search</span>
              </a>
            </li>
          </ul>
          <!-- End Navbar Toolbar -->
    
          <!-- Navbar Toolbar Right -->
          <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
            <li class="nav-item dropdown">
              <a class="nav-link navbar-avatar" data-toggle="dropdown" href="#" aria-expanded="false"
                data-animation="scale-up" role="button">
                <span class="avatar avatar-online">
                  <img src="global/portraits/5.jpg" alt="...">
                  <i></i>
                </span>
              </a>
              <div class="dropdown-menu" role="menu">
                <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon wb-power" aria-hidden="true"></i> Logout</a>
              </div>
            </li>
          </ul>
          <!-- End Navbar Toolbar Right -->
        </div>
        <!-- End Navbar Collapse -->
    
        <!-- Site Navbar Seach -->
        <div class="collapse navbar-search-overlap" id="site-navbar-search">
          <form role="search">
            <div class="form-group">
              <div class="input-search">
                <i class="input-search-icon wb-search" aria-hidden="true"></i>
                <input type="text" class="form-control" name="site-search" placeholder="Search...">
                <button type="button" class="input-search-close icon wb-close" data-target="#site-navbar-search"
                  data-toggle="collapse" aria-label="Close"></button>
              </div>
            </div>
          </form>
        </div>
        <!-- End Site Navbar Seach -->
      </div>
    </nav>    
    <div class="site-menubar">
      <div class="site-menubar-body">
        <div>
          <div>
            <ul class="site-menu" data-plugin="menu">
              <li class="site-menu-category">General</li>
              <li class="site-menu-item has-sub">
                <a href="javascript:void(0)">
                        <i class="site-menu-icon wb-dashboard" aria-hidden="true"></i>
                        <span class="site-menu-title">Dashboard</span>
                            <div class="site-menu-badge">
                                <span class="badge badge-pill badge-success">3</span>
                            </div>
                </a>
              </li>
              <li class="site-menu-item has-sub">
                <a href="javascript:void(0)">
                        <i class="site-menu-icon wb-layout" aria-hidden="true"></i>
                        <span class="site-menu-title">Kelola</span>
                                <span class="site-menu-arrow"></span>
                    </a>
                <ul class="site-menu-sub">
                  <li class="site-menu-item">
                    <a class="animsition-link" href="anggota-kelompok.html">
                      <span class="site-menu-title">Anggota Kelompok</span>
                    </a>
                  </li>
                  <li class="site-menu-item">
                    <a class="animsition-link" href="populasi-kelompok.html">
                      <span class="site-menu-title">Populasi Kelompok</span>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
{% endblock  %}

aplikasi/templates/otentikasi/daftar.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block konten %}
<div class="page vertical-align text-center" data-animsition-in="fade-in" data-animsition-out="fade-out">>
      <div class="page-content vertical-align-middle animation-slide-top animation-duration-1">
        <div class="brand">
          <img class="brand-img" src="/static/assets/images/logo.png" alt="Aplikasi Prediksi Estrus Sapi Perah">
          <h2 class="brand-text">KPSP Setia Kawan - Nongkojajar</h2>
        </div>
        <p>Silahkan login untuk mengakses aplikasi</p>
        
            {{ wtf.quick_form(fm) }}
        <br>
        <p>Sudah punya akun? <a href="{{ url_for('auth.masuk') }}">Silahkan Masuk</a></p>
        <footer class="page-copyright page-copyright-inverse">
          <p>Skripsi Randy Anwar</p>
          <p>© 2018. Universitas Narotama.</p>
        </footer>
      </div>
    </div>
{% endblock  %}

aplikasi/templates/otentikasi/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block konten %}
<div class="page vertical-align text-center" data-animsition-in="fade-in" data-animsition-out="fade-out">>
      <div class="page-content vertical-align-middle animation-slide-top animation-duration-1">
        <div class="brand">
          <img class="brand-img" src="/static/assets/images/logo.png" alt="Aplikasi Prediksi Estrus Sapi Perah">
        </div>
        <p>Silahkan login untuk mengakses aplikasi</p>
            {{ wtf.quick_form(fm) }}
        <br>
        <p>Belum punya akun? <a href="{{ url_for('auth.daftar') }}">Silahkan Daftar</a></p>
        <footer class="page-copyright page-copyright-inverse">
          <p>Skripsi Randy Anwar</p>
          <p>© 2019. Universitas Narotama.</p>
        </footer>
      </div>
    </div>
{% endblock  %}

aplikasi/templates/otentikasi/masuk.html
{% extends 'layout.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block isi_content %}
    <h1>Masuk Aplikasi</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(fm) }}
        </div>
    </div>
    <br>
    <p>Belum punya akun? <a href="{{ url_for('auth.daftar') }}">Silahkan Daftar</a></p>
{% endblock %}

aplikasi/templates/pkb/pkb_add.html
{% extends 'app.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block konten %}
    <div class="col-xxl-4 col-lg-12">
        <div class="panel">
            <div class="panel-heading">
            <h3 class="panel-title">Transaksi Pemeriksaan Kebuntingan Sapi</h3>
            </div>
            <div class="col-lg-6 offset-lg-3">
                {{ wtf.quick_form(fm) }}
                <br/>
            </div>
        </div>
    </div>
{% endblock %}

aplikasi/templates/sapi/sapi_add.html
{% extends 'app.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block konten %}
    <div class="col-xxl-4 col-lg-12">
        <div class="panel">
            <div class="panel-heading">
            <h3 class="panel-title">Menambah Sapi</h3>
            </div>
            <div class="col-lg-6 offset-lg-3">
                {{ wtf.quick_form(fm) }}
                <br/>
            </div>
        </div>
    </div>
{% endblock %}

aplikasi/templates/wilayah/wilayah_add.html
{% extends 'app.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block konten %}
    <div class="col-xxl-4 col-lg-12">
        <div class="panel">
            <div class="panel-heading">
            <h3 class="panel-title">Menambah Sapi</h3>
            </div>
            <div class="col-lg-6 offset-lg-3">
                {{ wtf.quick_form(fm) }}
                <br/>
            </div>
        </div>
    </div>
{% endblock %}